### ISSUE TITLE
More runtime compatibility

### ISSUE THREAD

**Issue by Airkro** [sindresorhus/clean-stack#28]
`p-*` function is useful, thank you for your great work.

Recently I had some trouble when I use them in some non `node.js` runtime, without bundler.

The error cause by:

`p-*` -> https://github.com/sindresorhus/aggregate-error -> https://github.com/sindresorhus/clean-stack/blob/main/index.js#L1

There is no `os` module in non `node.js` runtime.

So, it's possible to stop using `aggregate-error` in `p-*`?

**Comment by Airkro** [comment]
I understand why `aggregate-error` matters now, but I don't think `clean-stack` has to be a part of it, native `AggregateError` doesn't have it (I guess).

Remove `clean-stack` or `cleanStack.options.pretty` could be the way, not that pretty but more compatibility?

**Comment by sindresorhus** [comment]
I'm not interested in making breaking changes to `aggregate-error`. It work differently from the native error type as it was made years before the native error type was introduced.

I have outlined the solution in https://github.com/sindresorhus/clean-stack/issues/28#issuecomment-917834014

**Comment by fregante** [comment]
I think solving this issue for the browser is easy:

```diff
- import os from 'os';
+ import os from './os';
```

Then have

```js
// os.js
export {default} from 'os'

// os-browser.js
export default {homedir: ''};
````

The only problem is that bundler compatibility is spotty and I'm not sure about the modern equivalent of the [`browser` field of package.json](https://github.com/defunctzombie/package-browser-field-spec).

I think I've seen this pattern being used with the `exports` field somewhere in Sindre’s repo. Anyone remembers how to do it and whether the major bundlers support it? Worst case scenario those bundlers keep using `os` instead of `{homedir: ''}`

**Comment by silverwind** [comment]
This new [`imports`](https://nodejs.org/api/packages.html#imports) usage seems to break at least Jest which apparently does not support such resolution.

**Comment by sindresorhus** [comment]
It's up to Jest to support Node.js features.

**Comment by silverwind** [comment]
For anyone else ending up here: The Jest issue is tracked in https://github.com/facebook/jest/issues/12270, there seem to be workarounds available.
