### ISSUE TITLE
Clean stack rows only with /node_modules/babel-polyfill/

### ISSUE THREAD

**Issue by PredokMiF** [sindresorhus/clean-stack#8]
Util clean stacktrace rows only with `/node_modules/babel-polyfill/`
I expect that it clean all rows that contains `/node_modules/`

**Comment by sindresorhus** [comment]
Why should it do that? The error might have been thrown in a dependency of yours.

**Comment by PredokMiF** [comment]
Util clean only core stack lines like `module.js`, `babel` and others. But I think it isn't enough, because `node_modules` clog more, than core moules.

**Comment by sindresorhus** [comment]
I don't think you're getting my point. Think of `node_modules` as part of your codebase. It really is. You wouldn't want to exclude that as it would be impossible to debug if the error happens in a dependency. `/node_modules/babel-polyfill/` is only excluded because its callstack would never be useful.

**Comment by sindresorhus** [comment]
If you need something configurable, check out https://github.com/tapjs/stack-utils :)

**Comment by PredokMiF** [comment]
Ok, I will try it. Than you!
